[phases.setup]
nixPkgs = { php = "8.1", node = "18" }

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run production"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
